[versions]
springBoot = "4.0.0"
kotlin = "2.2.21"
nativeBuildTools = "0.11.3"

[libraries]
springBootStarter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
nativeBuildTools = { id = "org.graalvm.buildtools.native", version.ref = "nativeBuildTools" }
